version: '3.7'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
